services:
  api:
    build: .
    container_name: homemate-api
    command: gunicorn -w 4 -b 0.0.0.0:5000 "app:create_app()"
    volumes:
      - .:/app
      - ./instance:/app/instance
    ports:
      - "5000:5000"
    env_file:
      - ./app/.env
    depends_on:
      - redis

  redis:
    image: "redis:alpine"
    container_name: redis-server
    ports:
      - "6379:6379"

volumes:
  instance:
